#!/usr/bin/env zsh

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="nvim,ubersicht,yabai,task,tmux,zsh,htop,qutebrowser,karabiner,hammerspoon,ghostty"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES="$HOME/.dotfiles"
fi

pushd "$DOTFILES" >/dev/null || exit 1

for folder in ${(s:,:)STOW_FOLDERS}
do
    echo "stowing $folder"
    stow -D "$folder" 2>/dev/null
    stow "$folder"
done

popd >/dev/null
