#!/usr/bin/env zsh

export STOW_FOLDERS="${STOW_FOLDERS:-nvim,ubersicht,yabai,task,tmux,zsh,htop,qutebrowser,karabiner,hammerspoon,ghostty,keyboard}"
export DOTFILES="${DOTFILES:-$HOME/.dotfiles}"

echo "DOTFILES=$DOTFILES"
echo "STOW_FOLDERS=$STOW_FOLDERS"

"$DOTFILES/install"
