#!/usr/bin/env sh

# global settings
# yabai -m config mouse_follows_focus          off
# yabai -m config focus_follows_mouse          off

# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
#
# yabai -m config window_opacity_duration      0.0
# yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                on
yabai -m config window_border_width          5
#

# yabai -m config active_window_border_color   0xff3e5ea3
yabai -m config active_window_border_color   0xff36528f
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f

yabai -m config auto_balance                 off
yabai -m config split_ratio                  0.50

yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  15
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   2

# mission-control desktop labels
yabai -m space 1 --label home
yabai -m space 2 --label web
yabai -m space 3 --label term
yabai -m space 4 --label slack
yabai -m space 5 --label outlook
yabai -m space 6 --label spotify
yabai -m space 7 --label quip
yabai -m space 8 --label utils
yabai -m space 9 --label random
yabai -m space 10 --label webex

# specific space settings
yabai -m config --space utils layout        float
yabai -m config --space home layout           float

# window rules
yabai -m rule --add app="^Google Chrome$" space=web
yabai -m rule --add app="iTerm$" space=term
yabai -m rule --add app="Microsoft Outlook^$" space=outlook
yabai -m rule --add app="^Slack$" space=slack
yabai -m rule --add app="^Spotify$" space=spotify
yabai -m rule --add app="^Cisco Webex Meetings$" space=webex
yabai -m rule --add app="^Quip$" space=quip
yabai -m rule --add app="^System Preferences$" manage=off space=utils
yabai -m rule --add app="^Cisco AnyConnect Secure Mobility Client$" manage=off space=utils

# refresh my Übersicht bar when the space changes
yabai -m signal --add event=space_changed \
    action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"ubersicht-polybar-widget-left-bar-coffee\"'"
## If I close the active window, focus on any other visible window.
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"

echo "yabai configuration loaded.."
