#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off

yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                on
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff3e5ea3
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f

yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space setting
yabai -m config layout                       bsp
yabai -m config top_padding                  24
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# yabai -m space 1 --label one
# yabai -m space 2 --label two
# yabai -m space 3 --label three
# yabai -m space 4 --label four
# yabai -m space 5 --label five
# yabai -m space 6 --label six
# yabai -m space 9 --label nine

# mission-control desktop labels
yabai -m space 1 --label fun-browser
yabai -m space 2 --label work-browser
yabai -m space 3 --label terminal
yabai -m space 4 --label outlook
yabai -m space 5 --label slack
yabai -m space 6 --label spotify
yabai -m space 7 --label random
yabai -m space 8 --label webex
yabai -m space 9 --label utilities

# specific space settings
yabai -m config --space utilities layout        float
yabai -m config --space random layout           float

# window rules
yabai -m rule --add app="^Google Chrome$" space=fun-browser
yabai -m rule --add app="^Google Chrome$" space=work-browser
yabai -m rule --add app="iTerm$" space=terminal
yabai -m rule --add app="Microsoft Outlook^$" space=outlook
yabai -m rule --add app="^Slack$" space=slack
yabai -m rule --add app="^Spotify$" space=spotify
yabai -m rule --add app="^Cisco Webex Meetings$" space=webex
yabai -m rule --add app="^System Preferences$" manage=off space=utilities
yabai -m rule --add app="^Cisco AnyConnect Secure Mobility Client$" manage=off space=utilities

## If I close the active window, focus on any other visible window.
yabai -m signal --add event=window_destroyed action="bash /Users/_jacksanders/yabScripts/window-focus-on-destroy.sh"


# kill any existing limelight process if one exists, before we launch a new one
# killall limelight &> /dev/null
# limelight &> /dev/null &

echo "yabai configuration loaded.."
