local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node
--  t()  text_node | Static text that doesn't change
--  i()  insert_node | Editable placeholder (you jump between these)
--  f()  function_node | Dynamic text generated by a Lua function
--  c()  choice_node | Multiple options you can cycle through with <C-E>
--  s()  snippet | The wrapper that defines the whole snippet

return {
	-- Callouts
	s("note", {
		t(">[!NOTE]"),
		i(1),
	}),

	s("tip", {
		t(">[!TIP]"),
		i(1),
	}),

	s("important", {
		t(">[!IMPORTANT]"),
		i(1),
	}),

	s("warning", {
		t(">[!WARNING]"),
		i(1),
	}),

	s("caution", {
		t(">[!CAUTION]"),
		i(1),
	}),

	s("abstract", {
		t(">[!ABSTRACT]"),
		i(1),
	}),

	s("todo", {
		t(">[!TODO]"),
		i(1),
	}),

	s("subnote", {
		t(">[!SUBNOTE]"),
		i(1, "title"),
		t({ "", "```subnote", "" }),
		i(2, "note content here"),
		t({ "", "```", "" }),
		i(0),
	}),

	-- Code blocks
	s("code", {
		t("```"),
		i(1, "language"),
		t({ "", "" }),
		i(2, "code here"),
		t({ "", "```" }),
	}),
}
